# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170406_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=0, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
